### ISSUE TITLE
Do you support django>2.0?

### ISSUE THREAD

**Issue by Sashkow** [praekeltfoundation/django-google-analytics#51]
When I install your repo via pip install `django-google-analytics-app`, I get dependency conflict with django 2.0.9. Is there a compatible version and how to install it?

**Comment by ngati77** [comment]
Hi,
I installed the django-google-analytics-app and now my django version is forced to 1.11. It was django 2.1.3
Has anyone else report this issue? Looks like my enviornment is damaged...

Do you have support to Dajngo 2?

**Comment by rudigiesler** [comment]
There is currently no support for Django 2 at the moment. There are a few PRs that are currently in progress related to this:

https://github.com/praekeltfoundation/django-google-analytics/pull/54
https://github.com/praekeltfoundation/django-google-analytics/pull/53
https://github.com/praekeltfoundation/django-google-analytics/pull/38

**Comment by JayH5** [comment]
Fixed in #54
