### ISSUE TITLE
Middleware update for compatibility

### ISSUE THREAD

**Issue by ecowan** [praekeltfoundation/django-google-analytics#52]
Hi Everyone,

In order to work with the latest versions of Django, the middleware needs to inherit from MiddlewareMixin. I have made these changes and would be happy to create a PR if necessary. My fork of the project can be found here:

https://github.com/ecowan/django-google-analytics/commit/611a6309deba1b75a45e90da85048691d6a30a92

Thanks!

**Comment by JayH5** [comment]
Fixed in #54
