### ISSUE TITLE
Support django 2.x and celery 4

### ISSUE THREAD

**Issue by mrodal** [praekeltfoundation/django-google-analytics#56]
Hi, I see that the latest release doesnt support django 2.
Also, the version in master supports only up to 2.2, why not 2.x?

Is this incompatible with celery 4 for some reason? 

Are there plans to generate a new release?

Thanks

**Comment by rudigiesler** [comment]
Django portion solved by https://github.com/praekeltfoundation/django-google-analytics/pull/59

**Comment by rudigiesler** [comment]
Fixed in https://github.com/praekeltfoundation/django-google-analytics/pull/68
