### ISSUE TITLE
Uninstalling previously installed pip packages

### ISSUE THREAD

**Issue by saanpritom** [praekeltfoundation/django-google-analytics#61]
Hello,
I am trying to install the package using pip install django-google-analytics-app but during the installation it is uninstalling my previously installed packages and updating my pip automatically. It causes the breaking of the application. I am using Django 2.2 with Python 3.6 and Celery 4. Is it a bug or it is just not compatible with the versions?

**Comment by rudigiesler** [comment]
Hi @saanpritom 

You can find the requirements here: https://github.com/praekeltfoundation/django-google-analytics/blob/develop/setup.py#L25-L33

I think the issue with your project might be that this package is not compatible with Celery 4. The only requirements that we are strict on is Django 2.2 (at least 2.2.5) and Celery < 4

**Comment by rudigiesler** [comment]
It seems like the Celery requirement is from 3 years ago, so it's possible that things have been fixed since then.

If the tests can pass on Celery 4 then I think we can lift the requirement.

**Comment by saanpritom** [comment]
Thank you @rudigiesler for your reply. Yeah I understand the problem, It's the celery issue. Anyway I have fixed the problem using another package called Django-analytics.
