### ISSUE TITLE
Potential dependency conflicts between django-google-analytics-app and celery

### ISSUE THREAD

**Issue by NeolithEra** [praekeltfoundation/django-google-analytics#63]
Hi, as shown in the following full dependency graph of **_django-google-analytics-app_**, **_django-google-analytics-app_** requires **_celery <4.0_** ， while the installed version of **_celery (3.1.26.post2)_** ，**_django-celery 3.3.1_** requires **_celery <4.0,>=3.1.15_**.
According to Pip's “_first found wins_” installation strategy, **_celery 3.1.26.post2_** is the actually installed version.
Although the first found package version **_celery 3.1.26.post2_** just satisfies the later dependency constraint （**_celery <4.0,>=3.1.15_**), it will easily cause a build failure once the updated **_django-celery_** introduces a higher version of **_celery_**
According to the release history of **_django-celery_**, it habitually upgrates **_celery_** in its recent releases. For instance, **_django-celery 3.2.0_** upgrated celery’s constraint from **_>=3.1.1 to >=3.1.9_**,**_django-celery3.2.1_** upgrated celery’s constraint from **_>=3.1.9 to >=3.1.10_**, and **_django-celery 3.2.2_** upgrated celery’s constraint from **_>=3.1.10 to >=3.1.15_**. 

### Dependency tree
```
django-google-analytics-app - 4.4.1
| +- beautifulsoup4(install version:4.9.0 version range:*)
| | +- soupsieve(install version:2.0 version range:>1.2)
| | | +- backports.functools_lru_cache (install version: version range:*)
| +- celery(install version:3.1.26.post2 version range:<4.0)
| +- django(install version:3.0.6 version range:>=2.2.5,<3.1)
| +- django-celery(install version:3.3.1 version range:*)
| | +- celery(install version:3.1.26.post2 version range:<4.0,>=3.1.15)
| | +- django(install version:3.0.6 version range:>=1.8)
| | | +- asgiref (install version: version range:=3.2)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- requests(install version:2.23.0 version range:*)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version: version range:>=3.0.2,<4)
| | +- idna(install version: version range:>=2.5,<3)
| | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- six(install version:1.14.0 version range:*)
| +- structlog(install version:20.1.0 version range:*)
| | +- six(install version:1.14.0 version range:*) 
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Lose the version range of **_celery_** to be **_*_**.
2.	Remove your direct dependency **_celery_**, and use the **_celery_** transitively introduced by **_django- celery_**.
@sewagodimo Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by moh-moola** [comment]
@NeolithEra the version pin on the celery package is something that can be done without, the django-celery package however will need not be pinned to known working versions.

Issue will be addressed in next release.

**Comment by rudigiesler** [comment]
Fixed in https://github.com/praekeltfoundation/django-google-analytics/pull/68
