### ISSUE TITLE
google-analytics app removes django 

### ISSUE THREAD

**Issue by Ahmed7fathi** [praekeltfoundation/django-google-analytics#64]
i'm trying to install django-google-analtyics but it removes my django package and installing django 3 
i'm working with **django 2.1.5**
pip log:

> 

> Successfully built billiard anyjson
> Installing collected packages: amqp, anyjson, kombu, billiard, celery, asgiref, Django, django-celery, structlog, urllib3, certifi, idna, chardet, requests, soupsieve, beauti
> fulsoup4, django-google-analytics-app
>   Attempting uninstall: Django
>     Found existing installation: Django 2.1.5
>     Uninstalling Django-2.1.5:
>       Successfully uninstalled Django-2.1.5
>   Rolling back uninstall of Django

**Comment by rudigiesler** [comment]
Django 2.2.5 is the lowest version supported by this package. Django 2.1 is no longer supported: https://www.djangoproject.com/download/

If you work with 2.2.5 or newer, then the django version shouldn't be replaced when installing. If it is, then create a new issue with details around that.
