### ISSUE TITLE
New version with support for celery 5?

### ISSUE THREAD

**Issue by nemecek-filip** [praekeltfoundation/django-google-analytics#74]
Hello,

would it be possible to release new version with support for Celery 5? It has been merged to develop - https://github.com/praekeltfoundation/django-google-analytics/pull/73/files

Thanks. 

PS: Or does version 5.0.5 wait for other updates? Thanks

**Comment by rudigiesler** [comment]
Hi! The 5.0.4 release contains both the Django and the Celery version upgrade: https://github.com/praekeltfoundation/django-google-analytics/blob/develop/CHANGELOG.rst#504 . Let me know if you're having issues with Celery 5 and 5.0.4

**Comment by nemecek-filip** [comment]
It looks like, the version on PyPi doesn't contain this commit.

> The conflict is caused by:
    The user requested celery==5.2.3
    django-google-analytics-app 5.0.4 depends on celery<5.0.0

I have also checked the version files from here - https://pypi.org/project/django-google-analytics-app/5.0.4/#files and in `setup.py` there is `'celery<5.0.0' in the dependencies list 🤔

**Comment by rudigiesler** [comment]
Yeah thanks, seems like we'll need another release, I'll do that and fix the release notes now

**Comment by rudigiesler** [comment]
I've release 5.0.5 with Celery 5.0 support
